### ISSUE TITLE
Argument error when using rest-client-1.8.0

### ISSUE THREAD

**Issue by darrenleeweber** [ruby-rdf/rdf#174]
e.g. pry console error:
```
g = RDF::Graph.load('http://id.loc.gov/authorities/names/no99010609.rdf')
ArgumentError: wrong number of arguments (3 for 4)
from /home/dlweber/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/response.rb:13:in `create'
```

**Comment by gkellogg** [comment]
I can't reproduce this, the following is the output on my Mac:

```
[rdf] ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]

[rdf] bundle exec irb -r linkeddata
2.1.5 :001 > g = RDF::Graph.load('http://id.loc.gov/authorities/names/no99010609.rdf')
 => #<RDF::Graph:0x3fff9652706c(default)> 
2.1.5 :002 > g.count
 => 96 
```

with this bundle content:

```
Gems included by the bundle:
  * addressable (2.3.8)
  * builder (3.2.2)
  * bundler (1.7.9)
  * byebug (4.0.4)
  * celluloid (0.16.0)
  * coderay (1.1.0)
  * columnize (0.9.0)
  * crack (0.4.2)
  * diff-lcs (1.2.5)
  * domain_name (0.5.23)
  * ebnf (0.3.7)
  * equivalent-xml (0.5.1)
  * ffi (1.9.8)
  * formatador (0.2.5)
  * guard (2.12.5)
  * guard-compat (1.2.1)
  * guard-rspec (4.5.0)
  * haml (4.0.6)
  * hitimes (1.2.2)
  * htmlentities (4.3.3)
  * http-cookie (1.0.2)
  * json-ld (1.1.8 274934f)
  * link_header (0.0.8)
  * linkeddata (1.1.2 85dfa93)
  * listen (2.10.0)
  * lumberjack (1.0.9)
  * method_source (0.8.2)
  * mime-types (2.4.3)
  * mini_portile (0.6.2)
  * nenv (0.2.0)
  * net-http-persistent (2.9.4)
  * netrc (0.10.3)
  * nokogiri (1.6.6.2)
  * notiffany (0.0.6)
  * pry (0.10.1)
  * rake (10.4.2)
  * rb-fsevent (0.9.4)
  * rb-inotify (0.9.5)
  * rdf (1.1.10)
  * rdf-aggregate-repo (1.1.0)
  * rdf-isomorphic (1.1.0)
  * rdf-json (1.1.1)
  * rdf-microdata (2.0 6dc4c15)
  * rdf-n3 (1.1.2 a8ab4d9)
  * rdf-rdfa (1.1.5 3d27228)
  * rdf-rdfxml (1.1.3 d3422f2)
  * rdf-reasoner (0.2.1)
  * rdf-spec (1.1.5 10f5051)
  * rdf-trig (1.1.3.1)
  * rdf-trix (1.1.0)
  * rdf-turtle (1.1.5 d0b7e8d)
  * rdf-xsd (1.1.3 6ebc659)
  * redcarpet (3.2.2)
  * rest-client (1.8.0)
  * rspec (3.2.0)
  * rspec-core (3.2.2)
  * rspec-expectations (3.2.0)
  * rspec-its (1.2.0)
  * rspec-mocks (3.2.1)
  * rspec-support (3.2.2)
  * safe_yaml (1.0.4)
  * shellany (0.0.1)
  * slop (3.6.0)
  * sparql (1.1.4 b7b7873)
  * sparql-client (1.1.4 e120e27)
  * sxp (0.1.3 0b9562c)
  * thor (0.19.1)
  * tilt (2.0.1)
  * timers (4.0.1)
  * unf (0.1.4)
  * unf_ext (0.0.6)
  * webmock (1.20.4)
  * wirble (0.1.3)
  * yard (0.8.7.6)
```

I'll need more details about your setup. You might try cloning the rdf gem, doing a `bundle install` and see if you get the same results; this could result in some ruby or gem version, or platform difference.

**Comment by darrenleeweber** [comment]
Skipping the details and we might close this, maybe the culprit is rest-client-components, i.e.
```
[1] pry(main)> g = RDF::Graph.load('http://id.loc.gov/authorities/names/no99010609.rdf')
ArgumentError: wrong number of arguments (3 for 4)
from /home/dlweber/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/response.rb:13:in `create'
[2] pry(main)> wtf
Exception: ArgumentError: wrong number of arguments (3 for 4)
--
0: /home/dlweber/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/response.rb:13:in `create'
1: /home/dlweber/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-components-1.3.0/lib/restclient/components.rb:16:in `call'
2: /home/dlweber/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-components-1.3.0/lib/restclient/components.rb:136:in `execute'
3: /home/dlweber/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
4: /home/dlweber/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/resource.rb:51:in `get'
```

**Comment by darrenleeweber** [comment]
Migrated this to https://github.com/crohr/rest-client-components/issues/8

**Comment by gkellogg** [comment]
By adding rest-client-components to the gem, and requiring restclient/components, I can reproduce the error.

**Comment by ndushay** [comment]
Dang.  caching works with rest-client 1.7.3, but fails with 1.8.0; there's a vulnerability with 1.7.3.  As you might guess, we are using rest-client-components in order to use rack-cache with rest-client;  and we want to use rest-client v1.8.0 to avoid a vulnerability with cookies:  ("session fixation vulnerability via Set-Cookie headers in 30x redirection responses")

It appears the signature for RestClient::Response.create changed from 3 args to 4 with the upgrade to 1.8.0

https://github.com/rest-client/rest-client/commit/c215b22bdbcb988dcc40117ff45432b0db25175b

And this line is where it is a problem in the RDF gem:

https://github.com/ruby-rdf/rdf/blob/develop/lib/rdf/util/file.rb#L77

I was able to reproduce with a few lines from the self.open_file method (and yes, using rest-client-components gem):

[1] pry(main)> base_uri = "http://www.w3.org/ns/oa-context-20130208.json".to_s
=> "http://www.w3.org/ns/oa-context-20130208.json"
[2] pry(main)> client = RestClient::Resource.new(base_uri)
=> #<RestClient::Resource:0x007f9597228d80 @block=nil, @options={}, @url="http://www.w3.org/ns/oa-context-20130208.json">
[3] pry(main)> client.get({}) do |response, request, res, &blk|
[3] pry(main)*   p response.code
[3] pry(main)* end  
ArgumentError: wrong number of arguments (3 for 4)

I confess I got confused after this point.

**Comment by gkellogg** [comment]
Okay, thanks. It sounds like doing some runtime version checks for rest-client, and rest-client-components may be necessary to ensure that we use the appropriate yield signature.

**Comment by gkellogg** [comment]
See https://github.com/crohr/rest-client-components/pull/9 for a fix to the rest-client-components issue.
