### ISSUE TITLE
Revisit methods that return arrays versus enumerators

### ISSUE THREAD

**Issue by gkellogg** [ruby-rdf/rdf#192]
@bendiken said:

> Also, in 2.0 we could take a page from Ruby 2.0's new conventions that
> clarify which kinds of methods (e.g. String#chars) return arrays
> versus return enumerators. These were pretty vague back in the day
> when enumerators were brand spanking new, and our original interfaces
> were defined accordingly, so we could bring them in line with language
> conventions--probably no major changes needed.

**Comment by bendiken** [comment]
We'll have to have a careful think about this one, and look up the rationale that the core Ruby folks went by in making the core library changes, as one consequence of doing this would certainly be worse scaling characteristics for non-trivial repositories.

**Comment by gkellogg** [comment]
Indeed, I did a large re-factor to use enumerators throughout the query path for SPARQL, which had some terrible performance implications, so abandoned it (see https://github.com/ruby-rdf/rdf/commit/853a6b10c57125390222c2d10ec41f2bdb816268 and https://github.com/ruby-rdf/sparql/commit/299c856b78805ef586b6e73789aafa400efa6564). There are some inconsistencies in query enumerables which are unfortunate, but returning enumerators everywhere, rather than solution arrays (Solutions) provide to make tracing behavior quite difficult, and performance ended up being a nightmare. As useful as the enumerator pattern is, it doesn't always have useful performance characteristics.

**Comment by bendiken** [comment]
Right, I've seen some benchmarks to that effect.

However, there _is_ a trade-off between performance and scalability here: assuming all values will be consumed, returning arrays (Ruby 2.0+) is more efficient than returning enumerators (Ruby 1.9), but will certainly overflow memory when performed on large repositories.

The most practical position might be to define these methods as just returning something enumerable (in the Ruby sense), changing to returning arrays for our in-memory storage implementations, but still permitting scalable native backends to return enumerators.

**Comment by gkellogg** [comment]
Yes, that's pretty much what we do now: we return either arrays, or yield to a block. In many cases, wrapping the result in `Queryable#enum_for` or `Enumerable#enum_for`; this is most useful at the outer-most layers, but could be useful as a multiplexed cursor when doing a distributed operation to a partitioned dataset, for example.

**Comment by bendiken** [comment]
That's the other thing: the block form for these methods is now deprecated in Ruby 2+. For example, [`String#chars`](http://ruby-doc.org/core-2.2.0/String.html#method-i-chars) returns an array, and [`String#each_char`](http://ruby-doc.org/core-2.2.0/String.html#method-i-each_char) returns an enumerator or yields to a block when one is given.

So, that finally clarifies the confusion regarding the previous unclear overlap between the `#things` and `#each_thing` dichotomy that existed ever since 1.9, and that very much was encoded also into initial versions of RDF.rb, causing an extra headache for implementors of these interfaces. I was never happy about it.

We should follow suit here, methinks. That is, to conform to core language conventions, perhaps deprecating the block form for `#subjects` (etc) is the essential change to make here. And then to specify in the documentation that these methods should return an array whenever possible, but are permitted to return an enumerator in case the array construction would be too expensive or impossible.

@gkellogg @no-reply If that sounds OK to you guys, I'll add these notes to `CHANGES.md` for 2.0.

**Comment by gkellogg** [comment]
:+1:

**Comment by gkellogg** [comment]
@bendiken @no-reply You guys might want to check out the changes in the last commit. This is a resurrection of work I did in 2013 on changing query to return an enumerator, rather than an array of solutions. The biggest ramifications are in refactoring `Solutions` to be a module, rather than a sub-class of Array. There are some inconsistencies, as some methods (e.g. `#filter`) take a block do to the filtering, not to yield solutions.

There is companion work in rdf-spect and sparql to be consistent with these changes.
