### ISSUE TITLE
RDF::Reader validity and error handling is inconsistent

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf#211]
We have at least three different situations on failure cases for readers: 
  1. Output an error to stdout when parsing; return `true` when asking `valid?`
  1. Raise an error, refuse to initialize.
  1. Fail silently, return `true` on `valid?`.

With `validate: true`, *most* implementations raise an `RDF::ReaderError`. But:
  1. Some still initialize and return `true` on `valid?`
  1. Some output an error to stdout and return `true` when asking `valid?`

Could we standardize a set of behavior for `valid?`, `validate: true`, and `validate: false` and add tests to `rdf-spec`?

```ruby
['rdf', 'rdf/turtle', 'rdf/rdfxml', 'rdf/trig', 'rdf/trix'].each { |lib| require lib }

RDF::Reader.for(:ttl).new('blah').valid?
# ERROR With input 'blah': Invalid token "blah"} (found "blah")
# => true

RDF::Reader.for(:ntriples).new('blah').valid?
# RDF::ReaderError: ERROR [line 1] Expected subject (found: "blah")
#   ...[trace]

RDF::Reader.for(:nquads).new('blah').valid?
# RDF::ReaderError: ERROR [line 1] Expected subject (found: "blah")
#   ...[trace]

RDF::Reader.for(:trig).new('blah').valid?
# ERROR With input 'blah': Invalid token "blah"} (found "blah")
# => true

RDF::Reader.for(:trix).new('blah').valid?
# => true

RDF::Reader.for(:rdfxml).new('--!&*()blah--').valid?
# RuntimeError: root must be a proxy not a NilClass
#  ...[trace]
```

**Comment by gkellogg** [comment]
Yes, we need more consistency, and a better way to handle this equivalently between different readers.

When I was working on ref-tabular, I needed to make sure errors and warnings were kept separate, and made available to the calling environment. I attempted to do something similar with Turtle/TriG, but it requires more work on the EBNF layer.

Basically, my though is that readers should always keep track of errors and warnings encountered during parse. If called with `#validate!`, it should abort when the first error is found. Otherwise, it should collect errors and warnings, either in the provided array-like option for `:errors` or `:warnings`, or kept internally. The `#valid?` can return true if the content of the `:errors` object is empty after parsing (`#valid?` before parsing probably the same as `#validate?`. In any case, the errors and warnings should be available from the reader instance after parse is complete. If a `ReaderError` is through, the errors and warnings should be included in the instance of that exception.

If no errors or warnings arrays are provided, a reader _may_ use a log-like object to collect, which _may_ be bound to `STDERR` (thoughts?). I think that, when run from a UI such as the `rdf` executable, it should log to STDERR, otherwise, just collect warnings in an array (or log) which is available after parsing.

In the examples above, the `Reader.for().new('blah') instantiates a ready but doesn't actually parse. The `#valid?` method would detect that parsing had not been performed, turn on `:validate`, and catch the result of `#each_statement`, returning true or false. Otherwise, if parsing had completed, it would look to see if any errors were generated during parsing.

This is going to requiring touching every reader.

**Comment by gkellogg** [comment]
Regarding support in rdf-spec, if a reader provides an `invalid_input` variable, it can be used to verify this behavior, in different cases.

**Comment by no-reply** [comment]
That sounds like a pretty good sketch of the desired behavior. I think it's a major version, though, so I'm tagging this for 2.0. I may try to make improvements to some of the individual readers in the meanwhile.

> Regarding support in rdf-spec, if a reader provides an `invalid_input` variable, it can be used to verify this behavior, in different cases.

I think we should make `invalid_input` optional, defaulting to some plausible nonsense `"This is obviously not a valid %^&* graph!"`. That way you can override the content if needed, but need not worry about it in general.

**Comment by gkellogg** [comment]
You might see how the update RDF::Turtle::Reader does this using warnings and errors. Note that `#valid?` simply rescues `#validate!`, so it might not be what you're looking for. As an alternative, `#valid?` could see if reading had already occurred and return `true` if the `errors` array is empty; I'm not sure it's worth the complexity, though.

**Comment by gkellogg** [comment]
Note that the recently added RDF::Util::Logger offers some help here, if it is properly deployed. Message summaries are available in `#log_statistics` which can be used to see if there are any `:fatal` or `:error` messages logged, which would imply invalid input (or output).

Currently implemented in N-Triples, N-Quads and Turtle. More coming over time.

**Comment by gkellogg** [comment]
See 45bed1c04aa14f246990842e54ea7cde141fca2e and https://github.com/ruby-rdf/rdf-spec/commit/a51b4dc248401bd57970f18ad8a7d0cd6edcfa29.

This clarifies both Reader and Writer validity use cases. Gems may fail before comprehensive updates are made. @no-reply, close if you think this satisfies your concerns.
