### ISSUE TITLE
Statements w/ Blank Nodes can be duplicated in serialized output

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf#261]
The definition of blank node equality runs afoul of keyspace definition for Ruby Hashes. This leads to repeated inserts of blank nodes that satisfy `#==`, and the same `#id` and `#hash, when they are not exactly the same object.

```ruby
repo = RDF::Repository.new

repo.insert([RDF::Node.new('s'), RDF::URI('http://ex.org/p'), 'o'])
repo.insert([RDF::Node.new('s'), RDF::URI('http://ex.org/p'), 'o'])

repo.dump :ntriples
# => "_:s <http://ex.org/p> \"o\" .\n_:s <http://ex.org/p> \"o\" .\n"
```

A (proposed) failing test for this is at [rdf-spec](https://github.com/ruby-rdf/rdf-spec/compare/feature/equality?expand=1#diff-8f2db15096fa69057d25ca99e3b367e4R109). An alternate solution is to continue to fail that test, but check that internally unique blank nodes are reflected as such in serialized output.

**Comment by gkellogg** [comment]
This is a serializer issue, isn't it? There's a `:unique_bnodes` option to Writer that re-issues BNode identifiers because of this reason; mostly, people expect to see the same BNode identifier used when re-serializing, so it's not the default.

You are inserting two different nodes, so they should be two different statements.

Alternatively, Writer could scan the graph/repo to look for BNodes with the same id which are different nodes and modify the id; however, Writer doesn't operate on graph/repo, but on each statement coming in, so it would probably need to keep a local memory and this could get ugly.

**Comment by no-reply** [comment]
The proposed solutions to this are broken down into #262 and #263. The issue is represented correctly by those tickets.

Closing.
