### ISSUE TITLE
Clarify `DEFAULT_GRAPH`

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf#318]
The default graph behavior varies between `Repository`, `Queryable`, `Statement` and `Pattern`. One side effect is that the default `#query_pattern` implementation fails the `Queryable` shared examples.

```ruby
require 'rdf'
require 'rdf/spec'

statements = RDF::Spec.quads
statements.extend(RDF::Enumerable, RDF::Queryable)

pattern = RDF::Query::Pattern.new(nil, nil, nil, graph_name: false)

statements.count # => 95
statements.send(:query_pattern, pattern).count # => 95 (expecting 75)
```

`Statement` treats `false` and `nil` interchangeably as "no graph". `Pattern` treats both as a graph variable:

```ruby
pattern = RDF::Query::Pattern.new(nil, nil, nil, graph_name: false)
pattern.has_graph? # => false

pattern === RDF::Statement(:s, RDF::URI('p'), :o, graph_name: :a_graph) # => true
```

The default `Queryable#query_pattern` uses the `Pattern` definition, while `Repository` patches in its own interpretation. The tests for `Queryable` specify the `Repository` definition, but are never run on a base `Enumerable/Queryable` object.

Within `Repository` itself, we varyingly use a `DEFAULT_GRAPH` constant and a hard coded `false`.

**Comment by no-reply** [comment]
I have a branch with a plausible fix at https://github.com/ruby-rdf/rdf/tree/feature/dataset, but I'm planning to jettison that and rethink.

**Comment by gkellogg** [comment]
Probably, for 2.0, we should have removed the ability to query over all graphs (named and default) with no/nil graph_name. We also discussed replacing `false` with some constant. Hard to do much until a 3.0 release.

However, there should be a query able test which uses `Queryable` and not `Repository`.

**Comment by no-reply** [comment]
Here's a proposal for `2.2.0`:

  - Drop the `RDF::Queryable` spec requiring `false` to match statements without named graphs.
  - Add a shared_example run for a generic `Queryable`; this will pass without the above spec.
  - Define default graph behavior for `Dataset`.
    - Allow the interpretation of "default graph" where it is simply the union of the other graphs in the dataset; use that for the baseline `Dataset` and `Queryable`.
  - Keep the current behavior for `Repository`, `Pattern` and `Statement`

I think this would all be backwards compatible, and set us up well for further alignment in 3.0.

Thoughts?

**Comment by gkellogg** [comment]
Changing default graph behavior to be union is inconsistent with our existing practices (which, IMO, is valuable) of having a distinct default graph from named graphs. Both SPARQL and RDF define a Dataset of being composed of a single default graph and zero or more named graphs, although many implementations use the merge semantics. I believe this will cause a number of SPARQL tests to fail.

I think we need to preserve the separation between the default graph and named graphs. It's fair to say that a statement without a graph_name, with a `nil` graph_name, or with a `false` graph name (all _falsey_) should be considered the same. The difference comes when querying, in which not specifying a graph_name matches across the dataset. Changing this breaks current behavior, and arguably would require a 3.0, rather than a 2.2, release, but it's not clear if anyone actually depends on this behavior.

**Comment by no-reply** [comment]
I've updated the https://github.com/ruby-rdf/rdf/compare/feature/dataset branch with my latest on this. 

I think this avoids any breaking changes, gets us a viable `Dataset` interface, and aligns expectations for `RDF::Queryable` with long-standing reality. Documentation updates, both in `Dataset` and in `Queryable`/`Query` are still needed.

I ended up using the same `false` approach for default graph on `Dataset` as is used in `Repository`. It seems easiest to align them and take it from there. The spec for `Dataset`'s interface only requires that query results on the default graph are a (improper) subset of the  full results.

If this looks like it's the right set of interfaces, I'll aim to write the docs, release note, and wrap up any refactors next week.

cc: @bendiken
