### ISSUE TITLE
Spamming Deprecation Message because Enumerable uses Array()

### ISSUE THREAD

**Issue by abrisse** [ruby-rdf/rdf#350]
Enumerable uses Array() [here](https://github.com/ruby-rdf/rdf/blob/develop/lib/rdf/mixin/enumerable.rb#L314) and [here](https://github.com/ruby-rdf/rdf/blob/develop/lib/rdf/mixin/enumerable.rb#L125), which leads to call the method #to_ary which has been [deprecated](https://github.com/ruby-rdf/rdf/blob/5a66f20acb9742060f525905fbf49263def1cfc2/lib/rdf/mixin/enumerator.rb#L25).

That leads to a ton of deprecation messages.

To reproduce the problem easily (here version 2.2.3):

```ruby
repo = RDF::Repository.new
repo << [RDF.type, RDF.type, RDF.type]
repo.statements # => [DEPRECATION] RDF::Queryable::Enumerator#to_ary is deprecated ...
```

Solution: replace all the Array() with #to_a. I can submit a PR.

**Comment by gkellogg** [comment]
Unless you can fix the source to avoid the deprecation, the only real solution is to release version 3.0 and actually remove the interfaces. Unfortunately, the mere presence of `#to_ary` and `#to_hash` causes many problems.

In this case, you could use `repo.insert`, or something similar.

**Comment by gkellogg** [comment]
We should, however, ensure that appending an array can work in this post-`#to_ary` world, or update documentation accordingly.

**Comment by abrisse** [comment]
No sure I followed you: `repo.insert` does not solve the problem, since the problem is with the coercion operated on the `#statements` method.

Several solutions:

 * remove the deprecation message and make an alias  `to_ary` => `to_a`
 * replaces all coercions withan explicit `to_a` to avoid the deprecation by the gem itself

Any preference?

**Comment by gkellogg** [comment]
We determined that both `#to_ary` and `#to_hash` need to go, as they cause [implicit damage in call sequences](http://zverok.github.io/blog/2016-01-18-implicit-vs-expicit.html), with `#to_hash` being the biggest offender: the DEPRECATION is a step along the way, but the only complete solution is to remove them entirely, which requires a 3.0 release, as it's a breaking change. Doing such a release is quite involved because of all the `~> 2.x` dependencies. But it needs to happen eventually.

The second solution is what's required. I think we can probably handle this explicitly in `Writable#<<`. I can't get to this today, but if you want to take a crack at it and do a PR, that would be most appreciated, presuming that it solves your problem. Otherwise, I'll spend time on it either later today or tomorrow.
