### ISSUE TITLE
Is there a more 'elegant' way to do this?

### ISSUE THREAD

**Issue by markwilkinson** [ruby-rdf/rdf#424]
Hi Gregg!

No urgency on this because my code works, it's mostly a stylistic question:

```
    g = RDF::Graph.load("https://w3id.org/duchenne-proms")
    RDF::Vocabulary.from_graph(g, url: "https://w3id.org/duchenne-proms", class_name: "DDP")
    t = DDP.find_term("https://w3id.org/duchenne-proms#DDP_00064")
    pref = DDP.find("http://purl.org/dc/elements/1.1/").__prefix__
    t.properties[(pref.to_s + ":description").to_sym]
```

those last two lines are really ugly... I am sure there must be a better way to do it!?  Your APIs are always more 'elegant' than that :-)

Any suggestions welcome, but it's not urgent.  

Cheers!

**Comment by gkellogg** [comment]
Not at present, but this mechanism ends up being fragile due to load-order dependencies.

At the expense of increasing the vocabulary load size, I think it's probably wise to deprecate the use of PNames in vocabulary properties (other than the built-in symbols, such as `:type`) in favor of absolute IRIs. As a tide-over I'll make an update that allows either the PName or the full IRI to be used to find such properties. You're code would then look like the following:

    g = RDF::Graph.load("https://w3id.org/duchenne-proms")
    RDF::Vocabulary.from_graph(g, url: "https://w3id.org/duchenne-proms", class_name: "DDP")
    t = DDP.find_term("https://w3id.org/duchenne-proms#DDP_00064")
    t.properties[:"http://purl.org/dc/elements/1.1/"]

It should also be able to be indexed by casing to `#to_sym`, which would also allow strings, and `RDF::URI` instances. `RDF::Vocabulary::Term#properties` can take care of that, and support the use of PNames (with a deprecation warning) where the PName comes from that defined for a loaded vocabulary.

@doriantaylor would this address https://github.com/ruby-rdf/rdf-reasoner/issues/7?

**Comment by gkellogg** [comment]
@markwilkinson I've done an update which should allow you to always use absolute IRIs to lookup properties. It also allows "built-in" accessors, such as `:subClassOf`, to be looked up using their URI and continues to allow lookup by PName.

I've updated internal vocabularies to use absolute IRIs rather than PNames, and will eventually update vocabularies in rdf-vocab. After that, there is some deprecation notices that can be added that look for vocabularies still using PNames, and may warn if lookup is done by PName, but that may be more than required.

Other gems, such as rdf-reasoner, will get updates as well, after the dust has settled, and eventually this calls for a new release. Should be completely compatible though, at least up until the deprecations are enabled.

**Comment by markwilkinson** [comment]
Fantastic, thanks!MarkOn Feb. 14, 2021 00:50, Gregg Kellogg <notifications@github.com> wrote:
@markwilkinson I've done an update which should allow you to always use absolute IRIs to lookup properties. It also allows "built-in" accessors, such as :subClassOf, to be looked up using their URI and continues to allow lookup by PName.
I've updated internal vocabularies to use absolute IRIs rather than PNames, and will eventually update vocabularies in rdf-vocab. After that, there is some deprecation notices that can be added that look for vocabularies still using PNames, and may warn if lookup is done by PName, but that may be more than required.
Other gems, such as rdf-reasoner, will get updates as well, after the dust has settled, and eventually this calls for a new release. Should be completely compatible though, at least up until the deprecations are enabled.
