### ISSUE TITLE
RDF::Query#graph_name does not behave has documented

### ISSUE THREAD

**Issue by Richard-Degenne** [ruby-rdf/rdf#442]
# Description
In the documentation for `RDF::Query#initialize`, the description of the `:graph_name` parameter states that

> Names that are against unbound variables match either default or named graphs.
>
> -- https://www.rubydoc.info/github/ruby-rdf/rdf/RDF/Query#initialize-instance_method

Here is a minimal example showing that this is not the case.

# Reproduction

```ruby
require 'rdf'

repository = RDF::Repository.new

# Adding a statement in the default graph
repository << RDF::Statement.new(
  RDF::URI('http://www.example.com#alice'),
  RDF::URI('http://www.example.com#knows'),
  RDF::URI('http://www.example.com#bob')
)

# Adding a statement in a named graph
repository << RDF::Statement.new(
  RDF::URI('http://www.example.com#alice'),
  RDF::URI('http://www.example.com#knows'),
  RDF::URI('http://www.example.com#charlie'),
  graph_name: RDF::URI('http://www.example.com#named_graph')
)

query = RDF::Query.new(
  {
    RDF::URI('http://www.example.com#alice') => {
      RDF::URI('http://www.example.com#knows') => :friend
    }
  },
  graph_name: RDF::Query::Variable.new(:graph)
)

query.execute(repository)
```

## Expected behavior

The query should return two results:

- One with 
  - `graph: nil`
  - `friend: RDF::URI('http://www.example.com#bob')`
- One with
  - `graph: RDF::URI('http://www.example.com#named_graph')`
  - `friend: RDF::URI('http://www.example.com#charlie')`

## Actual behavior

Only the result in the named graph is returned. The result in the default graph is missing.

# Notes

This is particularly troublesome since this mechanism is the only way to execute a query against **all** graphs in a repository, both default and named.

## Workarounds

A way to work around this is to perform two queries, one against the default graph, and one against the named graphs, and aggregate the results.

```ruby
patterns = {
  RDF::URI('http://www.example.com#alice') => {
    RDF::URI('http://www.example.com#knows') => :friend
  }
}

default_query = RDF::Query.new(patterns, graph_name: false)
named_query = RDF::Query.new(patterns, graph_name: RDF::Query::Variable.new(:graph))

default_query.execute(repository) + named_query.execute(repository)
```

**Comment by gkellogg** [comment]
I think this is a case where the documentation is out of sync with the intended implementation. The fact that a variable does not match against the default graph stems from SPARQL semantics, where querying using an unbound graph name variable will not match the default graph. See [13.3.1 Accessing Graph Names](https://www.w3.org/TR/sparql11-query/#accessByLabel):

```sparql
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?src ?bobNick
FROM NAMED <http://example.org/foaf/aliceFoaf>
FROM NAMED <http://example.org/foaf/bobFoaf>
WHERE
  {
    GRAPH ?src
    { ?x foaf:mbox <mailto:bob@work.example> .
      ?x foaf:nick ?bobNick
    }
  }
```

Within RDF.rb, this happens because `RDF::Query::Variable#eql?(false)` always returns `false`, which it needs to do to be able to effectively do SPARQL queries. You can see how this is explicitly defined for `RDF::Repository#query_pattern`: https://github.com/ruby-rdf/rdf/blob/a889ba94b72d19f17bb66b57ebfa29ad00fbb4b5/lib/rdf/repository.rb#L405-L412

Of course, a different Repository implementation could do this differently, but I believe it would fail various SPARQL tests.

I believe the corrective action here is to update the method signatures in `RDF::Query` to match this behavior. I'm afraid I don't have an easy solution to query against both the default and named graphs and get back the bound graph name. If you query a repository without using a variable for the graph_name position, you will get back all solutions, but you will not know what graph the solution came from.

**Comment by Richard-Degenne** [comment]
> If you query a repository without using a variable for the graph_name position, you will get back all solutions, but you will not know what graph the solution came from.

I'll have to test that further, because I'm almost sure I have seen different behaviors.

**Comment by gkellogg** [comment]
> Ok, that makes sense. Thank you for the write-up!
> 
> I guess I'm also confused by the fact that I use the SPARQL gem to build queries, and the way it handles the default graph differs from the way our usual triple store handles it.
> 
> I'll leave the issue open for that adjustment in the documentation, but other than that, it's good for me.

Some triple stores treat the default graph as the union of all graphs in the dataset, but this is not a normative requirement. You can likely use the `MergeGraph` class from https://github.com/ruby-rdf/rdf-aggregate-repo/blob/3.3.0/lib/rdf/aggregate_repo/merge_graph.rb to simulate this behavior, but it could also be a pretty trivial wrapper around an RDF::Dataset/Repository as well.
